"""
Filename: mrms_reprojection.py
Author: Aldo Tapia
Date: 2026-07-09
Version: 0.1
Description: Script to reproject MRMS data to the AORC grid using xarray_regrid

FILE_AORC: path to the AORC netCDF file which is generated by NGIAB_data_preprocess
FILE_OUT: path to the output netCDF file which will contain the reprojected MRMS data
FILE_MRMS: path to the MRMS netCDF file which is generated by download_mrms.py
"""

import xarray as xr
from xarray_regrid import regrid
import pandas as pd
import numpy as np

FILE_AORC = "/Users/aldotapia/ngiab_preprocess_output/mrms-displacement/forcings/raw-gridded-data.nc"
FILE_OUT = "/Users/aldotapia/ngiab_preprocess_output/mrms-displacement/forcings/conus_nextgen_filtered_v2-raw-gridded-data.nc"
FILE_MRMS = "/Users/aldotapia/Documents/NPET_summer_institute_2026/data/mrms/GaugeCorr_QPE_01H_data.nc"

aorc_forcings = xr.open_dataset(FILE_AORC)
mrms_qpe = xr.open_dataset(FILE_MRMS, decode_cf=False)

mrms_qpe["time"] = pd.to_datetime(mrms_qpe["time"].values, unit="s")
mrms_qpe = mrms_qpe.sel(time=slice(aorc_forcings.time[0], aorc_forcings.time[-1]))

if not len(aorc_forcings.time) == len(mrms_qpe.time):
    raise ValueError("Time dimensions do not match")

mrms_qpe = mrms_qpe.rename({"longitude": "x", "latitude": "y"})

mrms_regridded = mrms_qpe.regrid.linear(aorc_forcings, time_dim="time")
mrms_regridded = mrms_regridded[["y", "x", "time", "qpe"]]
aorc_forcings["APCP_surface"].values = mrms_regridded["qpe"].values
aorc_forcings.to_netcdf(FILE_OUT, engine="netcdf4")
